apiVersion: v1
kind: Service
metadata:
  name: {{ template "factorio-server-charts.fullname" . }}
  labels:
    app: {{ template "factorio-server-charts.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: factorio
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.port }}
    {{- end }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: UDP
  selector:
    app: {{ template "factorio-server-charts.fullname" . }}
